### ISSUE TITLE
Add support for graphql fields

### ISSUE THREAD

**Issue by antoniogiroz** [rbutov/vscode-new-ui-dark-theme#1]
Hi!

Could you add support for fields in grahql/gql files?

In Webstorm:

<img width="518" alt="image" src="https://github.com/user-attachments/assets/b0cb8c0d-8d12-4ce9-bb08-bf6ac35b1af8">

In VSCode:

<img width="452" alt="image" src="https://github.com/user-attachments/assets/c960c539-b2c8-4c02-bb9f-525c792440ae">

At least the purple color for fields.

Thanks!

**Comment by rbutov** [comment]
@antoniogiroz hello, by default VS code doesn't have support for the graphql syntax,
what plugin do you use for the *.graphql ?

Thank you :)

**Comment by antoniogiroz** [comment]
I'm using these extensions:

- GraphQL: Language Feature Support (`graphql.vscode-graphql`)
- GraphQL: Syntax Highlighting (`graphql.vscode-graphql-syntax`)

**Comment by rbutov** [comment]
@antoniogiroz sorry for the loooong fix, was busy... 

fixed ;)

**Comment by rbutov** [comment]
@antoniogiroz sorry for the loooong fix, was busy...

fixed ;)
